-- 1: 

use UNIVER;

select GROUPS.FACULTY , PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT , avg(PROGRESS.NOTE) [—редн€€]
from  PROFESSION
inner join GROUPS   on PROFESSION.PROFESSION = GROUPS.PROFESSION and PROFESSION.PROFESSION_NAME like '»%'
inner join STUDENT  on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
group by rollup (GROUPS.FACULTY , PROGRESS.SUBJECT,PROFESSION.PROFESSION_NAME)




-- 2:

use UNIVER;

select GROUPS.FACULTY , PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT , avg(PROGRESS.NOTE) [—редн€€]
from  PROFESSION
inner join GROUPS   on PROFESSION.PROFESSION = GROUPS.PROFESSION and PROFESSION.PROFESSION_NAME like '»%'
inner join STUDENT  on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
group by cube (GROUPS.FACULTY , PROGRESS.SUBJECT,PROFESSION.PROFESSION_NAME)


-- 3,4:
select GROUPS.FACULTY , PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT , avg(PROGRESS.NOTE) [—редн€€]
from  PROFESSION
inner join GROUPS   on PROFESSION.PROFESSION = GROUPS.PROFESSION and PROFESSION.PROFESSION_NAME like '»з%'
inner join STUDENT  on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
group by GROUPS.FACULTY , PROGRESS.SUBJECT,PROFESSION.PROFESSION_NAME
union
select GROUPS.FACULTY , PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT , avg(PROGRESS.NOTE) [—редн€€]
from  PROFESSION
inner join GROUPS   on PROFESSION.PROFESSION = GROUPS.PROFESSION and PROFESSION.PROFESSION_NAME like '»н%'
inner join STUDENT  on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
group by GROUPS.FACULTY , PROGRESS.SUBJECT,PROFESSION.PROFESSION_NAME
intersect
select GROUPS.FACULTY , PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT , avg(PROGRESS.NOTE) [—редн€€]
from  PROFESSION
inner join GROUPS   on PROFESSION.PROFESSION = GROUPS.PROFESSION and PROFESSION.PROFESSION_NAME like '»з%'
inner join STUDENT  on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
group by GROUPS.FACULTY , PROGRESS.SUBJECT,PROFESSION.PROFESSION_NAME
union all
select GROUPS.FACULTY , PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT , avg(PROGRESS.NOTE) [—редн€€]
from  PROFESSION
inner join GROUPS   on PROFESSION.PROFESSION = GROUPS.PROFESSION and PROFESSION.PROFESSION_NAME like '»н%'
inner join STUDENT  on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
group by  GROUPS.FACULTY , PROGRESS.SUBJECT,PROFESSION.PROFESSION_NAME

-- 5:

select GROUPS.FACULTY , PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT , avg(PROGRESS.NOTE) [—редн€€]
from  PROFESSION
inner join GROUPS   on PROFESSION.PROFESSION = GROUPS.PROFESSION and PROFESSION.PROFESSION_NAME like '»з%'
inner join STUDENT  on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
group by GROUPS.FACULTY , PROGRESS.SUBJECT,PROFESSION.PROFESSION_NAME
union
select GROUPS.FACULTY , PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT , avg(PROGRESS.NOTE) [—редн€€]
from  PROFESSION
inner join GROUPS   on PROFESSION.PROFESSION = GROUPS.PROFESSION and PROFESSION.PROFESSION_NAME like '»н%'
inner join STUDENT  on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
group by GROUPS.FACULTY , PROGRESS.SUBJECT,PROFESSION.PROFESSION_NAME
except
select GROUPS.FACULTY , PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT , avg(PROGRESS.NOTE) [—редн€€]
from  PROFESSION
inner join GROUPS   on PROFESSION.PROFESSION = GROUPS.PROFESSION and PROFESSION.PROFESSION_NAME like '»з%'
inner join STUDENT  on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
group by GROUPS.FACULTY , PROGRESS.SUBJECT,PROFESSION.PROFESSION_NAME
union all
select GROUPS.FACULTY , PROFESSION.PROFESSION_NAME, PROGRESS.SUBJECT , avg(PROGRESS.NOTE) [—редн€€]
from  PROFESSION
inner join GROUPS   on PROFESSION.PROFESSION = GROUPS.PROFESSION and PROFESSION.PROFESSION_NAME like '»н%'
inner join STUDENT  on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
group by  GROUPS.FACULTY , PROGRESS.SUBJECT,PROFESSION.PROFESSION_NAME


-- 7 DOP: 

/*ѕодсчитать количество студентов в каждой группе, на каждом факультете и всего в университете одним запросом. */

select count(distinct IDSTUDENT)[ ол-во] , GROUPS.IDGROUP , FACULTY.FACULTY 
from STUDENT
inner join GROUPS on GROUPS.IDGROUP = STUDENT.IDGROUP
inner join FACULTY on FACULTY.FACULTY = GROUPS.FACULTY
group by rollup(FACULTY.FACULTY,GROUPS.IDGROUP)

/*ѕодсчитать количество аудиторий по типам и суммарной вместимости в корпусах и всего одним запросом.*/

select count(AUDITORIUM.AUDITORIUM)[количество аудиторий]  ,AUDITORIUM_TYPE.AUDITORIUM_TYPE, sum(AUDITORIUM.AUDITORIUM_CAPACITY) [суммарной вместимости] 
from AUDITORIUM_TYPE
full join AUDITORIUM  on AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE 
group by rollup(AUDITORIUM_TYPE.AUDITORIUM_TYPE)



